workflows:
  ionic-cordova-android-workflow:
    name: Ionic Cordova Android Workflow
    max_build_duration: 120
    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
      node: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies for Ionic Cordova project and update to Cordova version 7.1.0
        script: |
          npm ci # equivalent of npm install for CI systems. Requires package-lock.json or npm-shrinkwrap.json to be present
          npm i -g cordova@9.0.0
      - name: Setup Cordova Android platform
        script: |
          ionic cordova platform remove android --nosave
          ionic cordova platform add android@8.0.0 --confirm --no-interactive --noresources          
      - name: Build Android Cordova App
        script: |
          ionic cordova prepare android
          ionic cordova build android --release --no-interactive --prod --device   
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
